"""Render the v3 report figures with the existing Morandi renderer.

The report figures all come from ``output/figures/v3/data.json``, which is
generated by ``collect_v3_evidence.py`` from the frozen result files.  This
script adds no numbers of its own: it only maps that data onto chart specs and
hands them to the renderer already used by the earlier report versions, so the
visual language stays identical.

Two deliberate differences from the earlier figures:

* value labels are printed with a controlled number of decimals, because the
  default six decimals are unreadable once a chart carries nine bars;
* the architecture figure is rebuilt from ``build_english_architecture_figure``
  with the v3 training settings patched in, instead of duplicating that script.

All in-figure text is English and no figure carries a baked-in title.

Usage:
  ./.venv_project1/bin/python scripts/build_v3_figures.py [--skip-png]
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[2]
ROOT = PROJECT / 'code'
DATA = PROJECT / 'output/figures/v3/data.json'
OUT_DIR = PROJECT / 'output/figures/v3'

sys.path.insert(0, str(ROOT / 'scripts'))


def load_module(name: str, relpath: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / relpath)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


figures = load_module('journal_figures', 'scripts/build_english_journal_figures.py')

_original_fmt = figures.fmt


def fmt(value: float, chart: dict, precise: bool = False) -> str:
    """Renderer-compatible formatter with an explicit decimal budget."""
    tick_decimals = chart.get('decimals')
    if tick_decimals is None:
        return _original_fmt(value, chart, precise)
    decimals = chart.get('label_decimals', tick_decimals) if precise else tick_decimals
    return f'{value:.{decimals}f}'


figures.fmt = fmt


def chart(spec: dict) -> dict:
    return spec


def specs(data: dict) -> list[dict]:
    versions = data['versions']
    # JSON turns the float temperature keys into strings ("0.9", "1.075"), so
    # index by float rather than by a formatted label.
    temperature = {}
    for key, grid in data['temperature'].items():
        if not isinstance(grid, dict):
            continue
        try:
            temperature[key] = {float(k): v for k, v in grid.items()}
        except (TypeError, ValueError):
            continue  # e.g. the nested holdout summary, not a T grid

    def bpb_at(checkpoint: str, value: float) -> float:
        return temperature[checkpoint][value]

    return [
        {
            'id': 'v01_versions',
            'charts': [{
                'type': 'bar',
                'xTitle': '',
                'yTitle': 'Bits per byte (BPB)',
                'min': 1.4, 'max': 2.2, 'unit': 0.2,
                'decimals': 2, 'label_decimals': 3,
                'categories': [v['label'].replace('Frozen ', 'frozen ').replace('Course baseline', 'course\nbaseline')
                               for v in versions],
                'series': [
                    {'name': 'Validation (recipe only)',
                     'values': [v['validation'] for v in versions]},
                    {'name': 'Official test (frozen)',
                     'values': [v['test'] for v in versions]},
                ],
            }],
        },
        {
            'id': 'v02_horizon',
            'charts': [{
                'type': 'line',
                'xTitle': 'Processed training targets (millions)',
                'yTitle': 'Validation BPB',
                'min': 1.58, 'max': 1.66, 'unit': 0.02,
                'decimals': 3,
                'categories': [h['label'] for h in data['horizon']],
                'series': [{'name': 'seed 17, batch 32, full anneal',
                            'values': [h['value'] for h in data['horizon']]}],
            }],
        },
        {
            'id': 'v03_batch',
            'charts': [{
                'type': 'line',
                'xTitle': 'Batch size (windows per step, 20M targets)',
                'yTitle': 'Validation BPB',
                'min': 1.54, 'max': 1.68, 'unit': 0.02,
                'decimals': 3,
                'categories': [b['label'] for b in data['batch']],
                'series': [{'name': 'seed 17, full anneal',
                            'values': [b['value'] for b in data['batch']]}],
            }],
        },
        {
            'id': 'v04_lr',
            'charts': [{
                'type': 'line',
                'xTitle': 'Peak learning rate (batch 4, 28.9M targets)',
                'yTitle': 'Validation BPB',
                'min': 1.54, 'max': 1.61, 'unit': 0.01,
                'decimals': 3,
                'categories': [r['label'] for r in data['lr']],
                'series': [{'name': 'seed 17, full anneal',
                            'values': [r['value'] for r in data['lr']]}],
            }],
        },
        {
            'id': 'v05_capacity',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Width or depth at 20M targets, batch 32',
                'yTitle': 'Validation BPB',
                'min': 1.58, 'max': 1.64, 'unit': 0.01,
                'decimals': 3,
                'categories': [c['label'] for c in data['capacity']],
                'series': [{'name': 'seed 17', 'values': [c['value'] for c in data['capacity']]}],
            }],
        },
        {
            'id': 'v06_temperature',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Calibration temperature applied at inference',
                'yTitle': 'Validation BPB',
                'min': 1.53, 'max': 1.60, 'unit': 0.01,
                'decimals': 3,
                'categories': ['v2\nT = 1.00', 'v2\nT = 1.10', 'v3\nT = 1.00', 'v3\nT = 1.075'],
                'series': [{
                    'name': 'seed 17 for v3, seed 137 for v2',
                    'values': [bpb_at('v2', 1.0), bpb_at('v2', 1.1),
                               bpb_at('v3', 1.0), bpb_at('v3', 1.075)],
                }],
            }],
        },
        {
            'id': 'v07_noise',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Identical configuration, three separate runs',
                'yTitle': 'Validation BPB',
                'min': 1.59, 'max': 1.64, 'unit': 0.01,
                'decimals': 3,
                'categories': [n['label'] for n in data['noise']['runs']],
                'series': [{'name': 'seed 17, 28.9M, batch 32',
                            'values': [n['value'] for n in data['noise']['runs']]}],
            }],
        },
        {
            'id': 'v08_ablation_regularisation',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Training-only regularisation added to the batch-32 baseline',
                'yTitle': 'Validation BPB',
                'min': 1.59, 'max': 1.67, 'unit': 0.02,
                'decimals': 3,
                'categories': ['baseline', 'droppath\n0.1', 'embed\ndropout\n0.1',
                               'token\ndropout\n0.05'],
                'series': [{'name': '20M targets, seed 17', 'values': [
                    data['ablation']['baseline'],
                    *[r['value'] for r in data['ablation']['rows'][:3]],
                ]}],
            }],
        },
        {
            'id': 'v09_ablation_capacity',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Model shape changed away from width 320 / depth 8',
                'yTitle': 'Validation BPB',
                'min': 1.58, 'max': 1.64, 'unit': 0.01,
                'decimals': 3,
                'categories': ['baseline', 'depth\n9', 'width\n288', 'width\n256'],
                'series': [{'name': '20M targets, seed 17', 'values': [
                    data['ablation']['baseline'],
                    *[r['value'] for r in data['ablation']['rows'][4:7]],
                ]}],
            }],
        },
        {
            'id': 'v10_ablation_steps',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Optimisation steps per 20M processed targets',
                'yTitle': 'Validation BPB',
                'min': 1.54, 'max': 1.64, 'unit': 0.02,
                'decimals': 3,
                'categories': ['baseline\n2,442 steps', 'EMA\n0.999', 'batch 8\n9,766',
                               'batch 4\n19,531'],
                'series': [{'name': 'seed 17, full anneal', 'values': [
                    data['ablation']['baseline'],
                    data['ablation']['rows'][3]['value'],
                    data['ablation']['rows'][7]['value'],
                    data['ablation']['rows'][8]['value'],
                ]}],
            }],
        },
        {
            'id': 'v11_offset',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Frozen version',
                'yTitle': 'Test BPB minus validation BPB',
                'min': 0.015, 'max': 0.030, 'unit': 0.005,
                'decimals': 3, 'label_decimals': 4,
                'categories': [o['label'] for o in data['offset']],
                'series': [{'name': 'measured once per frozen predictor',
                            'values': [o['value'] for o in data['offset']]}],
            }],
        },
        {
            'id': 'v12_resources',
            'charts': [{
                'type': 'bar',
                'xTitle': '',
                'yTitle': 'Fraction of the course limit',
                'min': 0, 'max': 1, 'unit': 0.2,
                'format': '0%',
                'categories': ['CPU time\n/ 5x', 'Peak RSS\n/ 4 GiB', 'Inference assets\n/ 64 MiB'],
                'series': [
                    {'name': 'Frozen v2 (test)',
                     'values': [r['v2'] / r['limit'] for r in data['resources']['rows']]},
                    {'name': 'Frozen v3 (test)',
                     'values': [r['v3'] / r['limit'] for r in data['resources']['rows']]},
                ],
            }],
        },
    ]


def build_architecture() -> str:
    arch = load_module('journal_arch', 'scripts/build_english_architecture_figure.py')
    replacements = {
        'BatchLoader': ('BatchLoader', ['4 windows', '257 tokens each']),
        'AdamW update': ('AdamW update', ['lr = 1.5e-3', 'weight decay = 0.1']),
        'Cosine schedule': ('Cosine schedule', ['3% warmup', 'minimum lr = 0']),
        'Checkpoint': ('Checkpoint', ['10,488,640 parameters', '40.03 MiB']),
        'Frozen checkpoint': ('Frozen checkpoint', ['seed 17 selected', 'no test tuning']),
        'Test once after freeze': ('Test once after freeze',
                                   ['428,405 scored targets', 'final test BPB = 1.571349']),
    }
    patched = []
    for name in sorted(n for n in dir(arch) if n.endswith('_BOXES')):
        boxes = getattr(arch, name)
        for index, (title, _) in enumerate(boxes):
            if title in replacements:
                boxes[index] = replacements[title]
                patched.append(title)
    missing = set(replacements) - set(patched)
    if missing:
        raise SystemExit(f'architecture patch missed: {sorted(missing)}')
    return arch.build(), arch.W, arch.H


def write_png(svg_path: Path, png_path: Path, width: int = 2560, height: int = 1440) -> None:
    import cairosvg
    cairosvg.svg2png(url=str(svg_path), write_to=str(png_path),
                     output_width=width, output_height=height)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--skip-png', action='store_true')
    args = parser.parse_args()

    data = json.loads(DATA.read_text(encoding='utf-8'))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    manifest = []

    for spec in specs(data):
        svg_text = figures.render_figure(spec['id'], '', '', '', spec['charts'])
        svg_path = OUT_DIR / f"{spec['id']}.svg"
        svg_path.write_text(svg_text, encoding='utf-8')
        has_cjk = any('\u4e00' <= ch <= '\u9fff' for ch in svg_text)
        if not args.skip_png:
            write_png(svg_path, OUT_DIR / f"{spec['id']}.png")
        manifest.append({'id': spec['id'], 'png': f"{spec['id']}.png", 'cjk': has_cjk})
        print(f"{'CJK!' if has_cjk else ' ok '} {spec['id']}")

    svg_text, width, height = build_architecture()
    svg_path = OUT_DIR / 'v13_architecture.svg'
    svg_path.write_text(svg_text, encoding='utf-8')
    has_cjk = any('\u4e00' <= ch <= '\u9fff' for ch in svg_text)
    if not args.skip_png:
        write_png(svg_path, OUT_DIR / 'v13_architecture.png',
                  width=2560, height=round(2560 * height / width))
    manifest.append({'id': 'v13_architecture', 'png': 'v13_architecture.png', 'cjk': has_cjk})
    print(f"{'CJK!' if has_cjk else ' ok '} v13_architecture")

    (OUT_DIR / 'manifest.json').write_text(
        json.dumps(manifest, indent=1) + '\n', encoding='utf-8')
    bad = [m['id'] for m in manifest if m['cjk']]
    if bad:
        raise SystemExit(f'figures contain CJK text: {bad}')
    print(f'\n{len(manifest)} figures -> {OUT_DIR.relative_to(PROJECT)}')


if __name__ == '__main__':
    main()
