"""Render the v3 report figures with the existing Morandi renderer.

The report figures all come from ``output/figures/v3/data.json``, which is
generated by ``collect_v3_evidence.py`` from the frozen result files.  This
script adds no numbers of its own: it only maps that data onto chart specs and
hands them to the renderer already used by the earlier report versions, so the
visual language stays identical.

Two deliberate differences from the earlier figures:

* value labels are printed with a controlled number of decimals, because the
  default six decimals are unreadable once a chart carries nine bars;
* the architecture figure is rebuilt from ``build_english_architecture_figure``
  with the v3 training settings patched in, instead of duplicating that script.

All in-figure text is English and no figure carries a baked-in title.

Usage:
  ./.venv_project1/bin/python scripts/build_v3_figures.py [--skip-png]
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[2]
ROOT = PROJECT / 'code'
DATA = PROJECT / 'output/figures/v3/data.json'
OUT_DIR = PROJECT / 'output/figures/v3'

sys.path.insert(0, str(ROOT / 'scripts'))


def load_module(name: str, relpath: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / relpath)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


figures = load_module('journal_figures', 'scripts/build_english_journal_figures.py')

_original_fmt = figures.fmt


def fmt(value: float, chart: dict, precise: bool = False) -> str:
    """Renderer-compatible formatter with an explicit decimal budget."""
    tick_decimals = chart.get('decimals')
    if tick_decimals is None:
        return _original_fmt(value, chart, precise)
    decimals = chart.get('label_decimals', tick_decimals) if precise else tick_decimals
    return f'{value:.{decimals}f}'


figures.fmt = fmt


def chart(spec: dict) -> dict:
    return spec


def esc(text: str) -> str:
    return (str(text).replace('&', '&amp;').replace('<', '&lt;')
            .replace('>', '&gt;').replace('"', '&quot;'))


def specs(data: dict) -> list[dict]:
    versions = data['versions']
    # JSON turns the float temperature keys into strings ("0.9", "1.075"), so
    # index by float rather than by a formatted label.
    temperature = {}
    for key, grid in data['temperature'].items():
        if not isinstance(grid, dict):
            continue
        try:
            temperature[key] = {float(k): v for k, v in grid.items()}
        except (TypeError, ValueError):
            continue  # e.g. the nested holdout summary, not a T grid

    def bpb_at(checkpoint: str, value: float) -> float:
        return temperature[checkpoint][value]

    return [
        {
            'id': 'v01_versions',
            'charts': [{
                'type': 'bar',
                'xTitle': '',
                'yTitle': 'Bits per byte (BPB)',
                'min': 1.4, 'max': 2.2, 'unit': 0.2,
                'decimals': 2, 'label_decimals': 3,
                'categories': [v['label'].replace('Frozen ', 'frozen ').replace('Course baseline', 'course\nbaseline')
                               for v in versions],
                'series': [
                    {'name': 'Validation (recipe only)',
                     'values': [v['validation'] for v in versions]},
                    {'name': 'Official test (frozen)',
                     'values': [v['test'] for v in versions]},
                ],
            }],
        },
        {
            'id': 'v02_horizon',
            'charts': [{
                'type': 'line',
                'xTitle': 'Processed training targets (millions)',
                'yTitle': 'Validation BPB',
                'min': 1.58, 'max': 1.66, 'unit': 0.02,
                'decimals': 3,
                'categories': [h['label'] for h in data['horizon']],
                'series': [{'name': 'seed 17, batch 32, full anneal',
                            'values': [h['value'] for h in data['horizon']]}],
            }],
        },
        {
            'id': 'v03_batch',
            'charts': [{
                'type': 'line',
                'xTitle': 'Batch size (windows per step, 20M targets)',
                'yTitle': 'Validation BPB',
                'min': 1.54, 'max': 1.68, 'unit': 0.02,
                'decimals': 3,
                'categories': [b['label'] for b in data['batch']],
                'series': [{'name': 'seed 17, full anneal',
                            'values': [b['value'] for b in data['batch']]}],
            }],
        },
        {
            'id': 'v04_lr',
            'charts': [{
                'type': 'line',
                'xTitle': 'Peak learning rate (batch 4, 28.9M targets)',
                'yTitle': 'Validation BPB',
                'min': 1.54, 'max': 1.61, 'unit': 0.01,
                'decimals': 3,
                'categories': [r['label'] for r in data['lr']],
                'series': [{'name': 'seed 17, full anneal',
                            'values': [r['value'] for r in data['lr']]}],
            }],
        },
        {
            'id': 'v05_capacity',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Width or depth at 20M targets, batch 32',
                'yTitle': 'Validation BPB',
                'min': 1.58, 'max': 1.64, 'unit': 0.01,
                'decimals': 3,
                'categories': [c['label'] for c in data['capacity']],
                'series': [{'name': 'seed 17', 'values': [c['value'] for c in data['capacity']]}],
            }],
        },
        {
            'id': 'v06_temperature',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Calibration temperature applied at inference',
                'yTitle': 'Validation BPB',
                'min': 1.53, 'max': 1.60, 'unit': 0.01,
                'decimals': 3,
                'categories': ['v2\nT = 1.00', 'v2\nT = 1.10', 'v3\nT = 1.00', 'v3\nT = 1.075'],
                'series': [{
                    'name': 'seed 17 for v3, seed 137 for v2',
                    'values': [bpb_at('v2', 1.0), bpb_at('v2', 1.1),
                               bpb_at('v3', 1.0), bpb_at('v3', 1.075)],
                }],
            }],
        },
        {
            'id': 'v07_noise',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Identical configuration, three separate runs',
                'yTitle': 'Validation BPB',
                'min': 1.59, 'max': 1.64, 'unit': 0.01,
                'decimals': 3,
                'categories': [n['label'] for n in data['noise']['runs']],
                'series': [{'name': 'seed 17, 28.9M, batch 32',
                            'values': [n['value'] for n in data['noise']['runs']]}],
            }],
        },
        {
            'id': 'v08_ablation_regularisation',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Training-only regularisation added to the batch-32 baseline',
                'yTitle': 'Validation BPB',
                'min': 1.59, 'max': 1.67, 'unit': 0.02,
                'decimals': 3,
                'categories': ['baseline', 'droppath\n0.1', 'embed\ndropout\n0.1',
                               'token\ndropout\n0.05'],
                'series': [{'name': '20M targets, seed 17', 'values': [
                    data['ablation']['baseline'],
                    next(r['value'] for r in data['ablation']['rows'] if r['label'] == 'droppath 0.1'),
                    next(r['value'] for r in data['ablation']['rows'] if r['label'] == 'embed dropout 0.1'),
                    next(r['value'] for r in data['ablation']['rows'] if r['label'] == 'token drop 0.05'),
                ]}],
            }],
        },
        {
            'id': 'v09_ablation_capacity',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Model shape changed away from width 320 / depth 8',
                'yTitle': 'Validation BPB',
                'min': 1.58, 'max': 1.64, 'unit': 0.01,
                'decimals': 3,
                'categories': ['baseline', 'depth\n9', 'width\n288', 'width\n256'],
                'series': [{'name': '20M targets, seed 17', 'values': [
                    data['ablation']['baseline'],
                    *[r['value'] for r in data['ablation']['rows'][4:7]],
                ]}],
            }],
        },
        {
            'id': 'v10_ablation_steps',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Optimisation steps per 20M processed targets',
                'yTitle': 'Validation BPB',
                'min': 1.54, 'max': 1.64, 'unit': 0.02,
                'decimals': 3,
                'categories': ['baseline\n2,442 steps', 'EMA\n0.999', 'batch 8\n9,766',
                               'batch 4\n19,532'],
                'series': [{'name': 'seed 17, full anneal', 'values': [
                    data['ablation']['baseline'],
                    data['ablation']['rows'][3]['value'],
                    data['ablation']['rows'][7]['value'],
                    data['ablation']['rows'][8]['value'],
                ]}],
            }],
        },
        {
            'id': 'v11_offset',
            'charts': [{
                'type': 'bar',
                'xTitle': 'Frozen version',
                'yTitle': 'Test BPB minus validation BPB',
                'min': 0.015, 'max': 0.030, 'unit': 0.005,
                'decimals': 3, 'label_decimals': 4,
                'categories': [o['label'] for o in data['offset']],
                'series': [{'name': 'measured once per frozen predictor',
                            'values': [o['value'] for o in data['offset']]}],
            }],
        },
        {
            'id': 'v12_resources',
            'charts': [{
                'type': 'bar',
                'xTitle': '',
                'yTitle': 'Fraction of the course limit',
                'min': 0, 'max': 1, 'unit': 0.2,
                'format': '0%',
                'categories': ['CPU time\n/ 5x', 'Peak RSS\n/ 4 GiB', 'Inference assets\n/ 64 MiB'],
                'series': [
                    {'name': 'Frozen v2 (test)',
                     'values': [r['v2'] / r['limit'] for r in data['resources']['rows']]},
                    {'name': 'Frozen v3 (test)',
                     'values': [r['v3'] / r['limit'] for r in data['resources']['rows']]},
                ],
            }],
        },
    ]


def build_architecture() -> str:
    """Draw the exact v3 data flow, including residual paths and calibration."""
    width, height = 1600, 900

    def box(x: int, y: int, w: int, h: int, title: str, lines: list[str], fill: str) -> str:
        content = [f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="7" '
                   f'fill="{fill}" stroke="#75838A" stroke-width="1.4"/>',
                   f'<text class="head" x="{x + w / 2}" y="{y + 25}" text-anchor="middle">{esc(title)}</text>']
        for index, line in enumerate(lines):
            content.append(f'<text class="body" x="{x + w / 2}" y="{y + 46 + 17 * index}" '
                           f'text-anchor="middle">{esc(line)}</text>')
        return ''.join(content)

    def arrow(x1: float, y1: float, x2: float, y2: float, *, dashed: bool = False) -> str:
        dash = ' stroke-dasharray="7 5"' if dashed else ''
        return (f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="#4F5D63" '
                f'stroke-width="1.8"{dash} marker-end="url(#arrow)"/>')

    def path(points: list[tuple[float, float]], *, dashed: bool = False) -> str:
        coords = ' '.join(f'{"M" if i == 0 else "L"} {x} {y}' for i, (x, y) in enumerate(points))
        dash = ' stroke-dasharray="7 5"' if dashed else ''
        return (f'<path d="{coords}" fill="none" stroke="#4F5D63" stroke-width="1.8"{dash} '
                f'marker-end="url(#arrow)"/>')

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<style>text{font-family:Arial,Helvetica,sans-serif;fill:#20282D}'
        '.lane{font-size:18px;font-weight:700}.head{font-size:14px;font-weight:700}'
        '.body{font-size:12px}.note{font-size:12px;fill:#536168}</style>',
        '<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto">'
        '<path d="M0,0 L0,6 L9,3 z" fill="#4F5D63"/></marker></defs>',
        '<rect width="100%" height="100%" fill="#FFFFFF"/>',
        '<text class="lane" x="40" y="34">1  Training data</text>',
    ]

    lane1 = [
        ('WikiText-2 train', ['raw UTF-8 bytes']),
        ('Integrity check', ['SHA-256 manifest']),
        ('BPE tokenizer', ['fixed vocabulary 2048']),
        ('Token IDs', ['N = 3,613,343']),
        ('Batch loader', ['4 windows', '257 tokens each']),
        ('Shift targets', ['x = tokens[:-1]', 'y = tokens[1:]']),
    ]
    lane1_x = [40, 295, 550, 805, 1060, 1315]
    for index, ((title, lines), x0) in enumerate(zip(lane1, lane1_x)):
        parts.append(box(x0, 50, 210, 82, title, lines, '#EDF4F7'))
        if index:
            parts.append(arrow(lane1_x[index - 1] + 210, 91, x0, 91))

    parts.extend([
        path([(1420, 132), (1420, 190), (122, 190), (122, 258)]),
        '<text class="note" x="760" y="184" text-anchor="middle">input sequence x</text>',
    ])

    parts.extend([
        '<text class="lane" x="40" y="206">2  Decoder-only Transformer forward path</text>',
        box(40, 258, 165, 78, 'Token embedding', ['[B,T,320]', 'dropout = 0'], '#EEF6EF'),
        '<rect x="235" y="220" width="1035" height="300" rx="9" fill="#FAFBFB" '
        'stroke="#75838A" stroke-width="1.6"/>',
        '<text class="head" x="752" y="246" text-anchor="middle">Transformer block × 8</text>',
        box(260, 275, 105, 64, 'RMSNorm', ['pre-norm'], '#F1F3F4'),
        box(390, 275, 105, 64, 'Q, K, V', ['4 heads'], '#F1F3F4'),
        box(520, 275, 115, 64, 'RoPE', ['Q and K only'], '#F1F3F4'),
        box(660, 275, 150, 64, 'Causal attention', ['context 256'], '#F1F3F4'),
        box(835, 275, 115, 64, 'Output proj.', ['bias free'], '#F1F3F4'),
        box(975, 275, 125, 64, 'Residual add', ['x + attention'], '#F1F3F4'),
        arrow(205, 297, 260, 307), arrow(365, 307, 390, 307), arrow(495, 307, 520, 307),
        arrow(635, 307, 660, 307), arrow(810, 307, 835, 307), arrow(950, 307, 975, 307),
        path([(442, 339), (442, 358), (735, 358), (735, 339)]),
        '<text class="note" x="588" y="354" text-anchor="middle">V bypasses RoPE</text>',
        path([(235, 297), (235, 260), (1037, 260), (1037, 275)], dashed=True),
        '<text class="note" x="650" y="256" text-anchor="middle">attention residual</text>',
        box(300, 410, 105, 64, 'RMSNorm', ['pre-norm'], '#F1F3F4'),
        box(435, 410, 165, 64, 'SwiGLU FFN', ['hidden size 853'], '#F1F3F4'),
        box(630, 410, 130, 64, 'Down proj.', ['bias free'], '#F1F3F4'),
        box(790, 410, 125, 64, 'Residual add', ['x + FFN'], '#F1F3F4'),
        path([(1100, 307), (1140, 307), (1140, 387), (300, 387), (300, 410)]),
        arrow(405, 442, 435, 442), arrow(600, 442, 630, 442), arrow(760, 442, 790, 442),
        path([(1140, 387), (1140, 495), (852, 495), (852, 474)], dashed=True),
        '<text class="note" x="1005" y="490" text-anchor="middle">feed-forward residual</text>',
        path([(915, 442), (1240, 442), (1240, 297), (1300, 297)]),
        box(1300, 258, 120, 78, 'Final norm', ['RMSNorm'], '#EEF6EF'),
        box(1450, 248, 120, 98, 'Tied LM head', ['shared weights', 'raw logits'], '#EEF6EF'),
        arrow(1420, 297, 1450, 297),
        path([(1510, 346), (1510, 548), (140, 548), (140, 580)]),
        '<text class="note" x="825" y="542" text-anchor="middle">training logits</text>',
        '<text class="lane" x="40" y="568">3  Training update and checkpoint</text>',
        box(40, 580, 200, 76, 'Cross-entropy', ['all 256 positions'], '#FFF4E8'),
        box(285, 580, 190, 76, 'Backpropagation', ['gradient clip 1.0'], '#FFF4E8'),
        box(620, 580, 200, 76, 'AdamW update', ['weight decay 0.1', 'betas 0.9 / 0.95'], '#FFF4E8'),
        box(1020, 580, 250, 76, 'Checkpoint', ['10,488,640 parameters', '40.03 MiB'], '#FFF4E8'),
        arrow(240, 618, 285, 618),
        path([(475, 618), (570, 618), (570, 618), (620, 618)]),
        arrow(820, 618, 1020, 618),
        box(620, 675, 200, 66, 'Learning-rate schedule', ['3% warmup; cosine to 0', 'peak = 1.5e-3'], '#FEF8ED'),
        arrow(720, 675, 720, 656),
        path([(1145, 656), (1145, 760), (130, 760), (130, 800)]),
        path([(1525, 91), (1575, 91), (1575, 560), (220, 560), (220, 580)]),
        '<text class="note" x="1450" y="554" text-anchor="middle">shifted target y</text>',
        '<text class="lane" x="40" y="785">4  Validation selection, freeze, and one test evaluation</text>',
    ])

    lane4 = [
        ('Validation only', ['select recipe, seed,', 'and checkpoint']),
        ('Freeze manifest', ['checkpoint + code', 'hashes recorded']),
        ('Test windows', ['independent, causal', 'complete split']),
        ('Frozen student', ['same forward path', 'no state carried']),
        ('Logits / 1.075', ['temperature scaling']),
        ('Log-softmax', ['CPU FP32']),
        ('Target NLL / BPB', ['sum NLL / ln(2)', '/ raw UTF-8 bytes']),
    ]
    lane4_x = [40, 260, 480, 700, 920, 1140, 1360]
    lane4_w = [180, 180, 180, 180, 180, 180, 200]
    for index, ((title, lines), x0, w0) in enumerate(zip(lane4, lane4_x, lane4_w)):
        parts.append(box(x0, 800, w0, 78, title, lines, '#F2F0F7'))
        if index:
            parts.append(arrow(lane4_x[index - 1] + lane4_w[index - 1], 839, x0, 839))

    parts.append('</svg>')
    return ''.join(parts), width, height


def build_decision_flow() -> tuple[str, int, int]:
    """Show how each measured failure or gain changed the next experiment."""
    width, height = 1640, 930
    ink, line = '#26333A', '#73838A'
    blue = ('#F1F6F8', '#4F8099')
    green = ('#F2F7F4', '#5C907A')
    orange = ('#FBF5EE', '#A47D5F')
    purple = ('#F4F2F7', '#837495')

    def wrap_words(value: str, limit: int) -> list[str]:
        lines, current = [], ''
        for word in value.split():
            candidate = word if not current else f'{current} {word}'
            if current and len(candidate) > limit:
                lines.append(current)
                current = word
            else:
                current = candidate
        if current:
            lines.append(current)
        return lines

    def box(x: int, y: int, w: int, h: int, title: str, observations: list[str],
            decision: list[str], palette: tuple[str, str]) -> str:
        parts = [f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="13" fill="{palette[0]}" '
                 f'stroke="{palette[1]}" stroke-width="2.3"/>']
        title_lines = wrap_words(title, 29)
        for index, title_line in enumerate(title_lines):
            parts.append(f'<text class="head" x="{x + 24}" y="{y + 38 + index * 28}">{esc(title_line)}</text>')
        yy = y + 66 + len(title_lines) * 28
        for line_text in observations:
            for wrapped in wrap_words(line_text, 34):
                parts.append(f'<text class="body" x="{x + 24}" y="{yy}">{esc(wrapped)}</text>')
                yy += 26
        yy += 8
        parts.append(f'<text class="meaning" x="{x + 24}" y="{yy}">Observed consequence</text>')
        yy += 28
        for line_text in decision[:-1]:
            for wrapped in wrap_words(line_text, 34):
                parts.append(f'<text class="body" x="{x + 24}" y="{yy}">{esc(wrapped)}</text>')
                yy += 26
        final_lines = wrap_words(decision[-1], 31)
        final_y = y + h - 30 - (len(final_lines) - 1) * 25
        for index, final_line in enumerate(final_lines):
            parts.append(f'<text class="decision" x="{x + 24}" y="{final_y + index * 25}">{esc(final_line)}</text>')
        return ''.join(parts)

    def arrow(points: list[tuple[int, int]]) -> str:
        coords = ' '.join(f'{"M" if index == 0 else "L"} {x} {y}'
                          for index, (x, y) in enumerate(points))
        return (f'<path d="{coords}" fill="none" stroke="{line}" stroke-width="2.5" '
                f'marker-end="url(#arrow)"/>')

    svg = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<style>text{font-family:Arial,Helvetica,sans-serif}'
        f'.head{{font-size:22px;font-weight:700;fill:{ink}}}'
        f'.body{{font-size:18px;fill:{ink}}}'
        '.meaning{font-size:17px;font-weight:700;fill:#647178}'
        '.decision{font-size:18px;font-weight:700;fill:#3F7188}</style>',
        '<defs><marker id="arrow" markerWidth="11" markerHeight="11" refX="9" refY="3.5" orient="auto">'
        f'<path d="M0,0 L0,7 L10,3.5 z" fill="{line}"/></marker></defs>',
        '<rect width="100%" height="100%" fill="#FFFFFF"/>',
    ]
    xs = [35, 440, 845, 1250]
    top_y, bottom_y, box_w, box_h = 30, 500, 355, 345
    top = [
        ('1  Separate block effects',
         ['SwiGLU main effect −0.055444', 'RMSNorm main effect −0.005725',
          'interaction only +0.000879'],
         ['Most block gain comes from SwiGLU.', 'Keep RMSNorm + SwiGLU; test capacity.'], blue),
        ('2  Capacity and regularisation',
         ['w256 +0.022691; w288 +0.011753', 'dropout 0.05 +0.033451',
          'droppath 0.1 +0.045020'],
         ['Smaller models and added noise hurt.', 'Keep w320 d8; stop adding regularisation.'], blue),
        ('3  Position and extra components',
         ['RoPE improves two short seeds', 'untied mean gain only −0.006750',
          'EMA / MTP remain below noise'],
         ['RoPE is the only stable direction.', 'Run long RoPE with tied weights.'], green),
        ('4  Regression changes selection',
         ['first long run: 1.620751 at 19.66M', 'then 1.634776 at 28.91M',
          'three seeds choose 19.66M'],
         ['More targets do not ensure improvement.', 'Predeclare checks; freeze seed 137 as v2.'], green),
    ]
    for x, content in zip(xs, top):
        svg.append(box(x, top_y, box_w, box_h, *content))
    for index in range(3):
        svg.append(arrow([(xs[index] + box_w, top_y + box_h // 2),
                          (xs[index + 1], top_y + box_h // 2)]))
    svg.append(arrow([(xs[3] + box_w // 2, top_y + box_h),
                      (xs[3] + box_w // 2, 455), (xs[0] + box_w // 2, 455),
                      (xs[0] + box_w // 2, bottom_y)]))
    bottom = [
        ('5  Establish the noise floor',
         ['three identical runs: σ = 0.010213', '20M–28.9M horizon changes < 2σ',
          'single-point gains are unreliable'],
         ['Longer training is not a clean lever.', 'Hold target budget; require replications.'], orange),
        ('6  Scan batch at one budget',
         ['batch 32 → 8 → 4 improves', '1.605134 → 1.582448 → 1.568646',
          'batch 2 / 1 rebound at lr 1e-3'],
         ['Step count helps until noise dominates.', 'Keep batch 4; re-sweep learning rate.'], orange),
        ('7  Re-sweep rate and calibration',
         ['1.5e-3 and 2.5e-3 are close', 'intervening 2e-3 is weaker',
          'T = 1.075 gains 0.007392'],
         ['No continuous LR plateau is established.', 'Freeze 1.5e-3; compare calibrated scores.'], purple),
        ('8  Replicate the tempting alternative',
         ['bs2 + 2e-3 first appears better', 'replicate mean 1.551793',
          'calibrated v3 = 1.549498'],
         ['The apparent gain vanishes on replication.', 'Freeze v3; next use a paired batch × LR matrix.'], purple),
    ]
    for x, content in zip(xs, bottom):
        svg.append(box(x, bottom_y, box_w, box_h, *content))
    for index in range(3):
        svg.append(arrow([(xs[index] + box_w, bottom_y + box_h // 2),
                          (xs[index + 1], bottom_y + box_h // 2)]))
    svg.append('</svg>')
    return ''.join(svg), width, height


def write_png(svg_path: Path, png_path: Path, width: int = 2560, height: int = 1440) -> None:
    import cairosvg
    cairosvg.svg2png(url=str(svg_path), write_to=str(png_path),
                     output_width=width, output_height=height)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--skip-png', action='store_true')
    args = parser.parse_args()

    data = json.loads(DATA.read_text(encoding='utf-8'))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    manifest = []

    for spec in specs(data):
        svg_text = figures.render_figure(spec['id'], '', '', '', spec['charts'])
        svg_path = OUT_DIR / f"{spec['id']}.svg"
        svg_path.write_text(svg_text, encoding='utf-8')
        has_cjk = any('\u4e00' <= ch <= '\u9fff' for ch in svg_text)
        if not args.skip_png:
            write_png(svg_path, OUT_DIR / f"{spec['id']}.png")
        manifest.append({'id': spec['id'], 'png': f"{spec['id']}.png", 'cjk': has_cjk})
        print(f"{'CJK!' if has_cjk else ' ok '} {spec['id']}")

    svg_text, width, height = build_architecture()
    svg_path = OUT_DIR / 'v13_architecture.svg'
    svg_path.write_text(svg_text, encoding='utf-8')
    has_cjk = any('\u4e00' <= ch <= '\u9fff' for ch in svg_text)
    if not args.skip_png:
        write_png(svg_path, OUT_DIR / 'v13_architecture.png',
                  width=2560, height=round(2560 * height / width))
    manifest.append({'id': 'v13_architecture', 'png': 'v13_architecture.png', 'cjk': has_cjk})
    print(f"{'CJK!' if has_cjk else ' ok '} v13_architecture")

    svg_text, width, height = build_decision_flow()
    svg_path = OUT_DIR / 'v14_decision_flow.svg'
    svg_path.write_text(svg_text, encoding='utf-8')
    has_cjk = any('\u4e00' <= ch <= '\u9fff' for ch in svg_text)
    if not args.skip_png:
        write_png(svg_path, OUT_DIR / 'v14_decision_flow.png',
                  width=2560, height=round(2560 * height / width))
    manifest.append({'id': 'v14_decision_flow', 'png': 'v14_decision_flow.png', 'cjk': has_cjk})
    print(f"{'CJK!' if has_cjk else ' ok '} v14_decision_flow")

    (OUT_DIR / 'manifest.json').write_text(
        json.dumps(manifest, indent=1) + '\n', encoding='utf-8')
    bad = [m['id'] for m in manifest if m['cjk']]
    if bad:
        raise SystemExit(f'figures contain CJK text: {bad}')
    print(f'\n{len(manifest)} figures -> {OUT_DIR.relative_to(PROJECT)}')


if __name__ == '__main__':
    main()
